//@version=5
// ╔══════════════════════════════════════════════════════════════════════════════╗
// ║ Fair Value Gaps Module                                                       ║
// ║ Author: Abdullahi Amir Umar                                                 ║
// ╚══════════════════════════════════════════════════════════════════════════════╝

get_ohlc()=> [close[1], open[1], high, low, high[2], low[2]]

detect_fvg(show_fvg, fvg_tf)=>
    [src_c1, src_o1, src_h, src_l, src_h2, src_l2] = request.security(syminfo.tickerid, fvg_tf, get_ohlc())
    
    if show_fvg
        delta_per = (src_c1 - src_o1) / src_o1 * 100
        change_tf = timeframe.change(fvg_tf)
        threshold = fvg_auto ? ta.cum(math.abs(change_tf ? delta_per : 0)) / n * 2 : 0

        //FVG conditions
        bullish_fvg_cnd = src_l > src_h2 and src_c1 > src_h2 and delta_per > threshold and change_tf
        bearish_fvg_cnd = src_h < src_l2 and src_c1 < src_l2 and -delta_per > threshold and change_tf

        [bullish_fvg_cnd, bearish_fvg_cnd, src_h, src_l, src_h2, src_l2]