//@version=5
// ╔══════════════════════════════════════════════════════════════════════════════╗
// ║ Order Blocks Module                                                          ║
// ║ Author: Abdullahi Amir Umar                                                 ║
// ╚══════════════════════════════════════════════════════════════════════════════╝

// Order block coordinates function
ob_coord(use_max, loc, target_top, target_btm, target_left, target_right, target_type, target_mit)=>
    min = 99999999.
    max = 0.
    idx = 1

    ob_threshold = ob_filter == 'Atr' ? atr : cmean_range 

    if use_max
        for i = 1 to (n - loc)-1
            if high[i] - low[i] < ob_threshold[i] * 2
                max := math.max(high[i], max)
                min := max == high[i] ? low[i] : min
                idx := max == high[i] ? i : idx
    else
        for i = 1 to (n - loc)-1
            if high[i] - low[i] < ob_threshold[i] * 2
                min := math.min(low[i], min)
                max := min == low[i] ? high[i] : max
                idx := min == low[i] ? i : idx

    array.unshift(target_top, max)
    array.unshift(target_btm, min)
    array.unshift(target_left, time[idx])
    array.unshift(target_right, time[idx])
    array.unshift(target_type, use_max ? -1 : 1)
    array.unshift(target_mit, 0)